version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: ${CONTAINER_A}
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - ${FLASK_SERVER_PORT}:${FLASK_SERVER_PORT}
    restart: on-failure:0
    volumes:
      - .:/app
    depends_on:
      - weaviate
    env_file:
      - .env
  weaviate:
    image: semitechnologies/weaviate:1.23.10
    restart: on-failure:0
    ports:
     - ${WEAVIATE_CLIENT_PORT}:${WEAVIATE_CLIENT_PORT}
     - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: ${QUERY_DEFAULTS_LIMIT}
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: ${AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED}
      PERSISTENCE_DATA_PATH: ${PERSISTENCE_DATA_PATH}
      ENABLE_MODULES: ${ENABLE_MODULES}
      DEFAULT_VECTORIZER_MODULE: ${DEFAULT_VECTORIZER_MODULE}
      HUGGINGFACE_APIKEY: ${X_HUGGINGFACE_API_KEY}
      CLUSTER_HOSTNAME: ${CLUSTER_HOSTNAME}